// ui/board.js
//
// Draws the board as an SVG from data/mapGeometry.json, an original map
// generated by tools/buildMap.py (not a tracing of the printed board).
// Territories are tappable. Rendering is a pure function of game state,
// so it simply re-draws after every change.

const NS = 'http://www.w3.org/2000/svg';

const SHORT_NAMES = {
  rockOutcroppings: 'Rock Outcrop.', bightOfTheCliff: 'Bight', habbanyaRidgeFlat: 'Habbanya Ridge',
  habbanyaSietch: 'Habbanya Sietch', cielagoNorth: 'Cielago N.', cielagoEast: 'Cielago E.', cielagoSouth: 'Cielago S.',
  cielagoWest: 'Cielago W.', plasticBasin: 'Plastic Basin', imperialBasin: 'Imperial Basin', sihayaRidge: 'Sihaya Ridge',
  cielagoDepression: 'Cielago Depr.', falseWallSouth: 'False Wall S.', falseWallEast: 'False Wall E.',
  falseWallWest: 'False Wall W.', windPassNorth: 'Wind Pass N.', holeInTheRock: 'Hole in Rock',
  rimWallWest: 'Rim Wall W.', theGreaterFlat: 'Greater Flat', theGreatFlat: 'Great Flat', theMinorErg: 'Minor Erg'
};

const el = (tag, attrs = {}, parent) => {
  const node = document.createElementNS(NS, tag);
  for (const [k, v] of Object.entries(attrs)) node.setAttribute(k, v);
  if (parent) parent.appendChild(node);
  return node;
};

export function createBoard({ container, geometry, territoriesData, factionColors, onTap, onZoom }) {
  const [cx, cy] = geometry.center;
  const radius = geometry.radius;
  const svg = el('svg', { viewBox: geometry.viewBox.join(' '), class: 'board', role: 'img', 'aria-label': 'Map of Arrakis' });
  container.replaceChildren(svg);

  el('circle', { cx, cy, r: radius + 8, class: 'board__rim' }, svg);
  const territoryLayer = el('g', {}, svg);
  const sectorLayer = el('g', { class: 'board__sectors' }, svg);
  const stormLayer = el('g', {}, svg);
  const labelLayer = el('g', { class: 'board__labels' }, svg);
  const tokenLayer = el('g', {}, svg);

  // 18 sectors: decorative radial lines (sector membership of territories
  // is still awaiting the sector count, see docs/STORM_TODO.md).
  for (let i = 0; i < 18; i++) {
    const a = (i * 20 - 90) * Math.PI / 180;
    el('line', { x1: cx + 70 * Math.cos(a), y1: cy + 70 * Math.sin(a), x2: cx + radius * Math.cos(a), y2: cy + radius * Math.sin(a) }, sectorLayer);
  }

  // --- Zoom and pan -------------------------------------------------------
  // Pinch (two fingers) zooms, one finger drags once zoomed, the wheel
  // zooms on desktop. A pointer that moves more than a few pixels counts as
  // a drag, and suppresses the territory tap that would otherwise follow.
  const FULL = 1000, MIN_W = 260;
  const view = { x: 0, y: 0, w: FULL };
  let dragged = false;
  const pointers = new Map();
  let lastPinch = null;

  const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
  function applyView() {
    view.w = clamp(view.w, MIN_W, FULL);
    view.x = clamp(view.x, 0, FULL - view.w);
    view.y = clamp(view.y, 0, FULL - view.w);
    svg.setAttribute('viewBox', `${view.x} ${view.y} ${view.w} ${view.w}`);
    onZoom?.(view.w < FULL - 1);
  }
  // Screen point to map coordinates (the SVG letterboxes to a square).
  function toMap(clientX, clientY) {
    const r = svg.getBoundingClientRect();
    const size = Math.min(r.width, r.height);
    const ox = r.left + (r.width - size) / 2, oy = r.top + (r.height - size) / 2;
    return { x: view.x + ((clientX - ox) / size) * view.w, y: view.y + ((clientY - oy) / size) * view.w, size };
  }
  function zoomAt(mx, my, factor) {
    const newW = clamp(view.w / factor, MIN_W, FULL);
    const k = newW / view.w;
    view.x = mx - (mx - view.x) * k;
    view.y = my - (my - view.y) * k;
    view.w = newW;
    applyView();
  }

  svg.addEventListener('pointerdown', e => {
    pointers.set(e.pointerId, { x: e.clientX, y: e.clientY, startX: e.clientX, startY: e.clientY });
    if (pointers.size === 1) dragged = false;
  });
  svg.addEventListener('pointermove', e => {
    const p = pointers.get(e.pointerId);
    if (!p) return;
    if (Math.hypot(e.clientX - p.startX, e.clientY - p.startY) > 8) dragged = true;
    if (pointers.size === 2) {
      const [a, b] = [...pointers.values()];
      p.x = e.clientX; p.y = e.clientY;
      const dist = Math.hypot(a.x - b.x, a.y - b.y);
      const mid = toMap((a.x + b.x) / 2, (a.y + b.y) / 2);
      if (lastPinch) zoomAt(mid.x, mid.y, dist / lastPinch);
      lastPinch = dist;
      dragged = true;
      return;
    }
    if (dragged && view.w < FULL) {
      const { size } = toMap(e.clientX, e.clientY);
      view.x -= ((e.clientX - p.x) / size) * view.w;
      view.y -= ((e.clientY - p.y) / size) * view.w;
      applyView();
    }
    p.x = e.clientX; p.y = e.clientY;
  });
  const release = e => {
    pointers.delete(e.pointerId);
    if (pointers.size < 2) lastPinch = null;
    // Let this gesture's click be ignored, then accept taps again.
    if (dragged) setTimeout(() => { if (!pointers.size) dragged = false; }, 50);
  };
  svg.addEventListener('pointerup', release);
  svg.addEventListener('pointercancel', release);
  svg.addEventListener('wheel', e => {
    e.preventDefault();
    const m = toMap(e.clientX, e.clientY);
    zoomAt(m.x, m.y, e.deltaY < 0 ? 1.15 : 1 / 1.15);
  }, { passive: false });

  const paths = {};
  for (const [id, geo] of Object.entries(geometry.territories)) {
    const type = territoriesData.territories[id]?.type ?? 'sand';
    const path = el('path', { d: geo.path, class: `territory territory--${type}`, 'data-id': id, tabindex: 0, role: 'button',
      'aria-label': territoriesData.territories[id]?.name ?? id }, territoryLayer);
    path.addEventListener('click', () => { if (!dragged) onTap?.(id); });
    path.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onTap?.(id); } });
    paths[id] = path;
  }

  function label(id, geo) {
    const name = territoriesData.territories[id]?.name ?? id;
    // Short names wherever a full name would crowd its region; smaller
    // regions get smaller type so labels stay inside their territory.
    const text = SHORT_NAMES[id] && (name.length > 11 || geo.area < 9000) ? SHORT_NAMES[id] : name;
    const size = geo.area < 6000 ? 12 : geo.area < 14000 ? 14 : 16;
    const t = el('text', { x: geo.label[0], y: geo.label[1] - 12, 'font-size': size, class: 'board__label' }, labelLayer);
    t.textContent = text;
  }
  for (const [id, geo] of Object.entries(geometry.territories)) label(id, geo);

  function render(state, { selected = null, highlight = [] } = {}) {
    for (const [id, path] of Object.entries(paths)) {
      path.classList.toggle('territory--selected', id === selected);
      path.classList.toggle('territory--highlight', highlight.includes(id));
    }

    // Storm: a shaded 20-degree wedge at the storm's sector.
    stormLayer.replaceChildren();
    if (state?.board?.stormPosition != null) {
      const start = (100 - state.board.stormPosition * 20) * Math.PI / 180;
      const end = start - 20 * Math.PI / 180;
      const p = a => `${cx + radius * Math.cos(a)},${cy + radius * Math.sin(a)}`;
      el('path', { d: `M${cx},${cy} L${p(start)} A${radius},${radius} 0 0 0 ${p(end)} Z`, class: 'board__storm' }, stormLayer);
    }

    tokenLayer.replaceChildren();
    if (!state) return;

    const spice = {};
    for (const m of state.board.spiceBlowMarkers) spice[m.territoryId] = (spice[m.territoryId] ?? 0) + m.amount;

    for (const [id, geo] of Object.entries(geometry.territories)) {
      const [lx, ly] = geo.label;
      const present = Object.entries(state.factions)
        .map(([f, faction]) => [f, faction.forces.onBoard[id] ?? 0, faction.forces.starredOnBoard?.[id] ?? 0])
        .filter(([, n]) => n > 0);
      const items = [...present.map(([f, n, s]) => ({ kind: 'force', f, n, s }))];
      if (spice[id]) items.push({ kind: 'spice', n: spice[id] });
      const step = 38;
      let x = lx - ((items.length - 1) * step) / 2;
      for (const item of items) {
        const g = el('g', { class: `token token--${item.kind}`, transform: `translate(${x},${ly + 14})` }, tokenLayer);
        if (item.kind === 'force') {
          el('circle', { r: 17, fill: factionColors[item.f] ?? '#333', class: 'token__disc' }, g);
          const t = el('text', { class: 'token__count', y: 6 }, g);
          t.textContent = item.n;
          if (item.s) el('circle', { r: 5, cx: 12, cy: -12, class: 'token__star' }, g);
        } else {
          el('rect', { x: -15, y: -15, width: 30, height: 30, rx: 6, transform: 'rotate(45)', class: 'token__spice-bg' }, g);
          const t = el('text', { class: 'token__count token__count--spice', y: 6 }, g);
          t.textContent = item.n;
        }
        x += step;
      }
    }
  }

  return {
    render,
    zoomBy: factor => zoomAt(view.x + view.w / 2, view.y + view.w / 2, factor),
    resetZoom: () => { view.x = 0; view.y = 0; view.w = FULL; applyView(); }
  };
}
