// ui/board.js
//
// Draws the board as an SVG from data/mapGeometry.json, an original map
// generated by tools/buildMap.py (not a tracing of the printed board).
// Territories are tappable. Rendering is a pure function of game state,
// so it simply re-draws after every change.

const NS = 'http://www.w3.org/2000/svg';

const SHORT_NAMES = {
  rockOutcroppings: 'Rock Outcrop.', bightOfTheCliff: 'Bight', habbanyaRidgeFlat: 'Habbanya Ridge',
  habbanyaSietch: 'Habbanya Sietch', cielagoNorth: 'Cielago N.', cielagoEast: 'Cielago E.', cielagoSouth: 'Cielago S.',
  cielagoWest: 'Cielago W.', plasticBasin: 'Plastic Basin', imperialBasin: 'Imperial Basin', sihayaRidge: 'Sihaya Ridge',
  cielagoDepression: 'Cielago Depr.', falseWallSouth: 'False Wall S.', falseWallEast: 'False Wall E.',
  falseWallWest: 'False Wall W.', windPassNorth: 'Wind Pass N.', holeInTheRock: 'Hole in Rock',
  rimWallWest: 'Rim Wall W.', theGreaterFlat: 'Greater Flat', theGreatFlat: 'Great Flat', theMinorErg: 'Minor Erg'
};

const el = (tag, attrs = {}, parent) => {
  const node = document.createElementNS(NS, tag);
  for (const [k, v] of Object.entries(attrs)) node.setAttribute(k, v);
  if (parent) parent.appendChild(node);
  return node;
};

export function createBoard({ container, geometry, territoriesData, factionColors, onTap }) {
  const [cx, cy] = geometry.center;
  const radius = geometry.radius;
  const svg = el('svg', { viewBox: geometry.viewBox.join(' '), class: 'board', role: 'img', 'aria-label': 'Map of Arrakis' });
  container.replaceChildren(svg);

  el('circle', { cx, cy, r: radius + 8, class: 'board__rim' }, svg);
  const territoryLayer = el('g', {}, svg);
  const sectorLayer = el('g', { class: 'board__sectors' }, svg);
  const stormLayer = el('g', {}, svg);
  const labelLayer = el('g', { class: 'board__labels' }, svg);
  const tokenLayer = el('g', {}, svg);

  // 18 sectors: decorative radial lines (sector membership of territories
  // is still awaiting the sector count, see docs/STORM_TODO.md).
  for (let i = 0; i < 18; i++) {
    const a = (i * 20 - 90) * Math.PI / 180;
    el('line', { x1: cx + 70 * Math.cos(a), y1: cy + 70 * Math.sin(a), x2: cx + radius * Math.cos(a), y2: cy + radius * Math.sin(a) }, sectorLayer);
  }

  const paths = {};
  for (const [id, geo] of Object.entries(geometry.territories)) {
    const type = territoriesData.territories[id]?.type ?? 'sand';
    const path = el('path', { d: geo.path, class: `territory territory--${type}`, 'data-id': id, tabindex: 0, role: 'button',
      'aria-label': territoriesData.territories[id]?.name ?? id }, territoryLayer);
    path.addEventListener('click', () => onTap?.(id));
    path.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onTap?.(id); } });
    paths[id] = path;
  }

  function label(id, geo) {
    const name = territoriesData.territories[id]?.name ?? id;
    // Short names wherever a full name would crowd its region; smaller
    // regions get smaller type so labels stay inside their territory.
    const text = SHORT_NAMES[id] && (name.length > 11 || geo.area < 9000) ? SHORT_NAMES[id] : name;
    const size = geo.area < 6000 ? 12 : geo.area < 14000 ? 14 : 16;
    const t = el('text', { x: geo.label[0], y: geo.label[1] - 12, 'font-size': size, class: 'board__label' }, labelLayer);
    t.textContent = text;
  }
  for (const [id, geo] of Object.entries(geometry.territories)) label(id, geo);

  function render(state, { selected = null, highlight = [] } = {}) {
    for (const [id, path] of Object.entries(paths)) {
      path.classList.toggle('territory--selected', id === selected);
      path.classList.toggle('territory--highlight', highlight.includes(id));
    }

    // Storm: a shaded 20-degree wedge at the storm's sector.
    stormLayer.replaceChildren();
    if (state?.board?.stormPosition != null) {
      const start = (100 - state.board.stormPosition * 20) * Math.PI / 180;
      const end = start - 20 * Math.PI / 180;
      const p = a => `${cx + radius * Math.cos(a)},${cy + radius * Math.sin(a)}`;
      el('path', { d: `M${cx},${cy} L${p(start)} A${radius},${radius} 0 0 0 ${p(end)} Z`, class: 'board__storm' }, stormLayer);
    }

    tokenLayer.replaceChildren();
    if (!state) return;

    const spice = {};
    for (const m of state.board.spiceBlowMarkers) spice[m.territoryId] = (spice[m.territoryId] ?? 0) + m.amount;

    for (const [id, geo] of Object.entries(geometry.territories)) {
      const [lx, ly] = geo.label;
      const present = Object.entries(state.factions)
        .map(([f, faction]) => [f, faction.forces.onBoard[id] ?? 0, faction.forces.starredOnBoard?.[id] ?? 0])
        .filter(([, n]) => n > 0);
      const items = [...present.map(([f, n, s]) => ({ kind: 'force', f, n, s }))];
      if (spice[id]) items.push({ kind: 'spice', n: spice[id] });
      const step = 38;
      let x = lx - ((items.length - 1) * step) / 2;
      for (const item of items) {
        const g = el('g', { class: `token token--${item.kind}`, transform: `translate(${x},${ly + 14})` }, tokenLayer);
        if (item.kind === 'force') {
          el('circle', { r: 17, fill: factionColors[item.f] ?? '#333', class: 'token__disc' }, g);
          const t = el('text', { class: 'token__count', y: 6 }, g);
          t.textContent = item.n;
          if (item.s) el('circle', { r: 5, cx: 12, cy: -12, class: 'token__star' }, g);
        } else {
          el('rect', { x: -15, y: -15, width: 30, height: 30, rx: 6, transform: 'rotate(45)', class: 'token__spice-bg' }, g);
          const t = el('text', { class: 'token__count token__count--spice', y: 6 }, g);
          t.textContent = item.n;
        }
        x += step;
      }
    }
  }

  return { render };
}
